### ISSUE TITLE
I got only single URL in sitemap after running command

### ISSUE THREAD

**Issue by prashantraval91185** [bringyourownideas/laravel-sitemap#8]
Hi,

I am working with the latest version of Laravel and just used your package to generate a sitemap for my website.

But when I visit the URL ( https://developercommunities.net/sitemap.xml ) it only shows the main domain, no other pages are scraped or added to the XML list.

Can you please help out me to sort this issue?

Thanks,

**Comment by spekulatius** [comment]
Hello @rawalprashant 

is your application server-side rendered? Pure JS isn't supported.

Cheers,
Peter

**Comment by prashantraval91185** [comment]
@spekulatius Hi, I am using Inertiajs and Vue JS for rendering.

**Comment by spekulatius** [comment]
Without pre-rendering this won't work (and is bad for SEO in general).

**Comment by prashantraval91185** [comment]
@spekulatius so do you mean the websites build with Vue or React are not ranking? Sorry, but I didn't get your point here can you please elaborate? Also, what do you suggest to solve this sitemap issue for the already build Vue site?

**Comment by spekulatius** [comment]
No, sites built using Vue and React *can* rank. Google gets better at indexing JS-based sites. But it still requires more work - server-side pre-rendering. Without SSR, you are likely to face issues getting pages indexed.

In regards to solutions: you can built the sitemap.xml yourself based on your data. Otherwise there might be other packages, but I haven't looked this really.

**Comment by prashantraval91185** [comment]
@spekulatius That's great, thank you for clearing my doubt regarding JS site ranking. You are right I have to check other packages which allowed SSR, I come to Nuxt JS by google result :)

**Comment by spekulatius** [comment]
Nuxt looks good from what I've seen so far. Good luck!
